In [1]:
import numpy as np

In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [4]:
print(v1)

[1 2 3]


In [5]:
print(v2)

[4 5 6]


In [7]:
v_add = v1 + v2

In [8]:
v_times = v1 * v2

In [9]:
print(v_times)

[ 4 10 18]


In [10]:
np.dot(v1, v2)

32

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [22]:
B = np.array([[1, 2, 3], [4, 5, 5], [7, 8, 9]])

In [15]:
e_value, e_vector = np.linalg.eig(B)
print(e_value)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [16]:
print(e_vector)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [23]:
A_inv = np.linalg.inv(B)
print(A_inv)

[[-0.83333333 -1.          0.83333333]
 [ 0.16666667  2.         -1.16666667]
 [ 0.5        -1.          0.5       ]]


In [25]:
print(np.dot(B, A_inv))

[[ 1.00000000e+00  0.00000000e+00  5.55111512e-17]
 [-2.22044605e-16  1.00000000e+00  1.66533454e-16]
 [ 2.22044605e-16  0.00000000e+00  1.00000000e+00]]
