In [14]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(b)
    for i in range(n):
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]         
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

A = [[3, 2, -4], [2, 3, 3], [5, -3, 1]]
b = [3, 15, 14]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [2.9999999999999996, 0.9999999999999996, 2.0]


In [16]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = np.array(A, dtype = float)
    
    for i in range(n):
        for j in range(i+1, n):
            if U[i,i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    return L, U

A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])
L, U = lu_decomposition(A)
print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]
